### ISSUE TITLE
no linux build

### ISSUE THREAD

**Issue by xylar** [conda-forge/cibots-feedstock#5]
It looks like no linux build happened for version 0.3:
https://anaconda.org/conda-forge/cibots/files
Not sure why this would be.  I'll try to bump the build number and rebuild tomorrow.

**Comment by doutriaux1** [comment]
@xylar thanks. I should actually make it no arch.

**Comment by xylar** [comment]
Yep, good plan!  I hadn't thought of that but would be an easy solution.
